- hosts: localhost
  connection: localhost
  gather_facts: false
  tasks:
    - name: Get facts from ec2 instances
      ec2_remote_facts:
        profile: "{{ boto_profile }}"
        region: "{{ aws_region }}"
        filters: "{{ host_filters }}"
      register: ec2_facts
    - name: add ec2 IPs to ansible virtual hosts
      add_host: hostname="{{ item.ip_address }}" groups="{{ item.tags.host_groups }}"
      with_items: "{{ ec2_facts.instances }}"
      changed_when: false
