---

- name: Fix permissions
  file: path="{{landing.install_path}}"
        owner="{{landing.install_user}}"
        state=directory
        recurse=yes
  tags:
    - landing

- name: Execute composer install on app path
  command: composer install chdir="{{landing.install_path}}"
  become: yes
  become_method: su
  become_user: "{{landing.install_user}}"
  register: composer_install
  failed_when: "composer_install.rc != 0"
  tags:
    - landing

- name: Execute bower install on www path
  command: bower install chdir="{{landing.install_path}}"
  become: yes
  become_method: su
  become_user: "{{landing.install_user}}"
  register: bower_install
  failed_when: "bower_install.rc != 0"
  tags:
    - landing

- name: Copy .env template file
  copy: remote_src="True"
        src="{{landing.install_path}}/.env.example"
        dest="{{landing.install_path}}/.env"
        owner="{{landing.install_user}}"
        mode="0640"
  tags:
    - landing

- name: Change .env to reflect real values (set in defaults/main.yml or in group_vars/ENV/..)
  lineinfile: backup=no
              dest="{{landing.install_path}}/.env"
              regexp="^{{item.key}}"
              line="{{item.key}}=\"{{item.value}}\""
              state=present
              owner="{{landing.install_user}}"
              mode="0640"
  with_dict: "{{ landing.app_env_vars }}"
  tags:
    - landing

- name: "Set cgi.fix_pathinfo=0"
  lineinfile: backup=yes
              dest="/etc/php.ini"
              regexp="^(;*)cgi\.fix_pathinfo=.*$"
              line="cgi.fix_pathinfo=0"
              state=present
              owner="{{landing.install_user}}"
              mode="0644"
  tags:
    - landing
