---

- name: "Include Nginx server_name into /etc/hosts file"
  lineinfile: line="127.0.0.1 {{beheard.nginx_config.server_name}}"
              insertafter="EOF"
              state="present"
              dest="/etc/hosts"
  tags:
    - common
 
