---
- name: Check if Drupal is already set up.
  stat: "path={{ drupal_core_path }}/index.php"
  register: drupal_site
  ignore_errors: true
  tags: drupal_install

- name: Define drush_path if it's not already defined.
  set_fact:
    drush_path: drush
  when: drush_path is not defined
  tags: drupal_install

- name: Define drupal_site_exists.
  set_fact:
    drupal_site_exists: "{{ drupal_site.stat.exists|default(false) }}"
  tags: drupal_install

# Deploy Drupal if configured.
- include_tasks: deploy.yml
  when: drupal_deploy
  tags: drupal_install

# Build with composer if configured.
- include_tasks: build-composer.yml
  when: drupal_build_composer
  tags: drupal_install

# Set Drush variables.
- name: Check if a project specific Drush binary exists.
  stat: "path={{ drupal_composer_install_dir }}/vendor/bin/drush"
  register: drush_vendor_bin
  ignore_errors: true
  tags: drupal_install

- name: Use project specific Drush if available.
  set_fact:
    drush_path: "{{ drupal_composer_install_dir }}/vendor/bin/drush"
  when: drush_vendor_bin.stat.exists
  tags: drupal_install

# Install site if configured.
- include_tasks: install-site.yml
  when: drupal_install_site
  tags: drupal_install
